### ISSUE TITLE
When running `docker compose up`, things break looking for `grouparoo/local-image`

### ISSUE THREAD

**Issue by evantahler** [grouparoo/app-example-docker#10]

**Comment by evantahler** [comment]
@rwfeather - do you happen to have any more details on the bug here?

**Comment by rwfeather** [comment]
@evantahler I was able to reproduce in a fresh env while following the steps in the readme:

<img width="1319" alt="Screen Shot 2022-01-02 at 4 04 11 PM" src="https://user-images.githubusercontent.com/6589528/147892839-9eaeb18e-e607-45ac-94b5-062f48eace0a.png">

Fix is: #12 

Not the most important thing to catch, but I figured I'd follow up on it.
